on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          sudo apt-get -y install musl-dev musl-tools 
          rustup target add x86_64-unknown-linux-musl
          cargo build --target x86_64-unknown-linux-musl --release
      - run: |
          echo -n ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin
          podman build -t ghcr.io/mossman1215/journeys-mastodon:latest .
